# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/XML-Atom-Microformats/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires
		"Test::More 0.61" ;
	:requires 
		"HTML::Microformats 0.100" ,
		"JSON 2.00" ,
		"RDF::RDFa::Parser 1.096" ,
		"RDF::Trine 0.135" ,
		"RDF::Query 2.900" ,
		"XML::Atom::OWL 0.100" ,
		"XML::LibXML 1.62" ,
		"common::sense" .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/XML/Atom/Microformats.pm" .

